/* Auto-generated by AuthSystem - 2026-06-07T03:02:22.321Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_73da4174-f72',
  apiKey: 'ak_development_bbe74fd5863e82137c099bacc14c54fc'
};
